// players.js - DATI CORRETTI E AGGIORNATI 2026
const PLAYERS = [
  {
    id: 1,
    name: "Lionel Messi",
    foot: "SX",
    nationality: "Argentina",
    role: "ATT",
    trophies: ["Champions League", "Mondiale", "Liga", "Ligue 1"],
    speciality: ["Punizioni", "Dribbling", "Visione"],
    height: 169,
    careerGoals: 896,
    image: "images/messi.jpg"
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    foot: "DX",
    nationality: "Portogallo",
    role: "ATT",
    trophies: ["Champions League", "Premier League", "Liga", "Serie A"],
    speciality: ["Rigori", "Finalizzazione", "Colpo di Testa"],
    height: 187,
    careerGoals: 915,
    image: "images/cristiano.jpg"
  },
  {
    id: 3,
    name: "Kylian Mbappé",
    foot: "DX",
    nationality: "Francia",
    role: "ATT",
    trophies: ["Champions League", "Mondiale", "Ligue 1"],
    speciality: ["Velocità", "Dribbling"],
    height: 178,
    careerGoals: 350,
    image: "images/mbappe.jpg"
  },
  {
    id: 4,
    name: "Virgil van Dijk",
    foot: "DX",
    nationality: "Paesi Bassi",
    role: "DIF",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Colpo di Testa", "Marcatura"],
    height: 193,
    careerGoals: 65,
    image: "images/vandijk.jpg"
  },
  {
    id: 5,
    name: "Manuel Neuer",
    foot: "DX",
    nationality: "Germania",
    role: "POR",
    trophies: ["Champions League", "Mondiale", "Bundesliga"],
    speciality: ["Sweeper Keeper", "Parate"],
    height: 193,
    careerGoals: 5,
    image: "images/neuer.jpg"
  },
  {
    id: 6,
    name: "Neymar Jr",
    foot: "DX",
    nationality: "Brasile",
    role: "ATT",
    trophies: ["Champions League", "Liga", "Ligue 1"],
    speciality: ["Dribbling", "Creatività"],
    height: 175,
    careerGoals: 481,
    image: "images/neymar.jpg"
  },
  {
    id: 7,
    name: "Robert Lewandowski",
    foot: "DX",
    nationality: "Polonia",
    role: "ATT",
    trophies: ["Champions League", "Bundesliga", "Liga"],
    speciality: ["Finalizzazione", "Posizionamento"],
    height: 185,
    careerGoals: 650,
    image: "images/lewandowski.jpg"
  },
  {
    id: 8,
    name: "Karim Benzema",
    foot: "DX",
    nationality: "Francia",
    role: "ATT",
    trophies: ["Champions League", "Liga"],
    speciality: ["Gioco di sponda", "Finalizzazione"],
    height: 185,
    careerGoals: 450,
    image: "images/benzema.jpg"
  },
  {
    id: 9,
    name: "Luka Modrić",
    foot: "DX",
    nationality: "Croazia",
    role: "CEN",
    trophies: ["Champions League", "Liga"],
    speciality: ["Visione", "Passaggi", "Leadership"],
    height: 172,
    careerGoals: 95,
    image: "images/modric.jpg"
  },
  {
    id: 10,
    name: "Kevin De Bruyne",
    foot: "DX",
    nationality: "Belgio",
    role: "CEN",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Passaggi", "Cross", "Tiri da fuori"],
    height: 181,
    careerGoals: 165,
    image: "images/debruyne.jpg"
  },
  {
    id: 11,
    name: "Erling Haaland",
    foot: "SX",
    nationality: "Norvegia",
    role: "ATT",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Finalizzazione", "Fisicità"],
    height: 194,
    careerGoals: 280,
    image: "images/haaland.jpg"
  },
  {
    id: 12,
    name: "Mohamed Salah",
    foot: "SX",
    nationality: "Egitto",
    role: "ATT",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Tagli in profondità", "Finalizzazione"],
    height: 175,
    careerGoals: 320,
    image: "images/salah.jpg"
  },
  {
    id: 13,
    name: "Sadio Mané",
    foot: "DX",
    nationality: "Senegal",
    role: "ATT",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Pressing", "Inserimenti"],
    height: 175,
    careerGoals: 230,
    image: "images/mane.jpg"
  },
  {
    id: 14,
    name: "Sergio Ramos",
    foot: "DX",
    nationality: "Spagna",
    role: "DIF",
    trophies: ["Champions League", "Liga"],
    speciality: ["Colpo di Testa", "Rigori"],
    height: 184,
    careerGoals: 135,
    image: "images/ramos.jpg"
  },
  {
    id: 15,
    name: "Gerard Piqué",
    foot: "DX",
    nationality: "Spagna",
    role: "DIF",
    trophies: ["Champions League", "Liga"],
    speciality: ["Impostazione dal basso"],
    height: 194,
    careerGoals: 55,
    image: "images/pique.jpg"
  },
  {
    id: 16,
    name: "Sergio Busquets",
    foot: "DX",
    nationality: "Spagna",
    role: "CEN",
    trophies: ["Champions League", "Liga"],
    speciality: ["Interdizione", "Posizionamento"],
    height: 189,
    careerGoals: 25,
    image: "images/busquets.jpg"
  },
  {
    id: 17,
    name: "Xavi Hernández",
    foot: "DX",
    nationality: "Spagna",
    role: "CEN",
    trophies: ["Champions League", "Liga"],
    speciality: ["Passaggi corti", "Regia"],
    height: 170,
    careerGoals: 85,
    image: "images/xavi.jpg"
  },
  {
    id: 18,
    name: "Andrés Iniesta",
    foot: "DX",
    nationality: "Spagna",
    role: "CEN",
    trophies: ["Champions League", "Liga"],
    speciality: ["Dribbling", "Inserimenti"],
    height: 171,
    careerGoals: 105,
    image: "images/iniesta.jpg"
  },
  {
    id: 19,
    name: "Thierry Henry",
    foot: "DX",
    nationality: "Francia",
    role: "ATT",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Contropiede", "Finalizzazione"],
    height: 188,
    careerGoals: 360,
    image: "images/henry.jpg"
  },
  {
    id: 20,
    name: "Zlatan Ibrahimović",
    foot: "DX",
    nationality: "Svezia",
    role: "ATT",
    trophies: ["Serie A", "Liga"],
    speciality: ["Acrobazie", "Fisicità", "Tecnica"],
    height: 195,
    careerGoals: 570,
    image: "images/ibrahimovic.jpg"
  },
  {
    id: 21,
    name: "Paolo Maldini",
    foot: "SX",
    nationality: "Italia",
    role: "DIF",
    trophies: ["Champions League", "Serie A"],
    speciality: ["Marcatura", "Anticipo"],
    height: 186,
    careerGoals: 40,
    image: "images/maldini.jpg"
  },
  {
    id: 22,
    name: "Franco Baresi",
    foot: "DX",
    nationality: "Italia",
    role: "DIF",
    trophies: ["Champions League", "Serie A"],
    speciality: ["Lettura del gioco"],
    height: 176,
    careerGoals: 20,
    image: "images/baresi.jpg"
  },
  {
    id: 23,
    name: "Andrea Pirlo",
    foot: "DX",
    nationality: "Italia",
    role: "CEN",
    trophies: ["Champions League", "Serie A"],
    speciality: ["Punizioni", "Lanci lunghi"],
    height: 177,
    careerGoals: 80,
    image: "images/pirlo.jpg"
  },
  {
    id: 24,
    name: "Gianluigi Buffon",
    foot: "DX",
    nationality: "Italia",
    role: "POR",
    trophies: ["Serie A"],
    speciality: ["Parate", "Leadership"],
    height: 192,
    careerGoals: 0,
    image: "images/buffon.jpg"
  },
  {
    id: 25,
    name: "Alisson Becker",
    foot: "DX",
    nationality: "Brasile",
    role: "POR",
    trophies: ["Champions League", "Premier League"],
    speciality: ["1 contro 1", "Gioco con i piedi"],
    height: 191,
    careerGoals: 1,
    image: "images/alisson.jpg"
  },
  {
    id: 26,
    name: "Ederson Moraes",
    foot: "SX",
    nationality: "Brasile",
    role: "POR",
    trophies: ["Premier League"],
    speciality: ["Lanci lunghi", "Sweeper Keeper"],
    height: 188,
    careerGoals: 1,
    image: "images/ederson.jpg"
  },
  {
    id: 27,
    name: "Trent Alexander-Arnold",
    foot: "DX",
    nationality: "Inghilterra",
    role: "DIF",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Cross", "Passaggi"],
    height: 175,
    careerGoals: 25,
    image: "images/trent.jpg"
  },
  {
    id: 28,
    name: "Andy Robertson",
    foot: "SX",
    nationality: "Scozia",
    role: "DIF",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Corsa", "Cross"],
    height: 178,
    careerGoals: 18,
    image: "images/robertson.jpg"
  },
  {
    id: 29,
    name: "João Cancelo",
    foot: "DX",
    nationality: "Portogallo",
    role: "DIF",
    trophies: ["Premier League"],
    speciality: ["Versatilità", "Cross"],
    height: 182,
    careerGoals: 30,
    image: "images/cancelo.jpg"
  },
  {
    id: 30,
    name: "Marcelo Vieira",
    foot: "SX",
    nationality: "Brasile",
    role: "DIF",
    trophies: ["Champions League", "Liga"],
    speciality: ["Dribbling", "Cross"],
    height: 174,
    careerGoals: 45,
    image: "images/marcelo.jpg"
  },
  {
    id: 31,
    name: "Toni Kroos",
    foot: "DX",
    nationality: "Germania",
    role: "CEN",
    trophies: ["Champions League", "Bundesliga"],
    speciality: ["Passaggi", "Gestione ritmi"],
    height: 183,
    careerGoals: 105,
    image: "images/kroos.jpg"
  },
  {
    id: 32,
    name: "Casemiro",
    foot: "DX",
    nationality: "Brasile",
    role: "CEN",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Interdizione", "Contrasti"],
    height: 185,
    careerGoals: 45,
    image: "images/casemiro.jpg"
  },
  {
    id: 33,
    name: "N'Golo Kanté",
    foot: "DX",
    nationality: "Francia",
    role: "CEN",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Recupero palla", "Pressing"],
    height: 168,
    careerGoals: 25,
    image: "images/kante.jpg"
  },
  {
    id: 34,
    name: "Paul Pogba",
    foot: "DX",
    nationality: "Francia",
    role: "CEN",
    trophies: ["Serie A"],
    speciality: ["Fisicità", "Tiri da fuori"],
    height: 191,
    careerGoals: 95,
    image: "images/pogba.jpg"
  },
  {
    id: 35,
    name: "Bruno Fernandes",
    foot: "DX",
    nationality: "Portogallo",
    role: "CEN",
    trophies: [],
    speciality: ["Rigori", "Passaggi chiave"],
    height: 179,
    careerGoals: 160,
    image: "images/bruno.jpg"
  },
  {
    id: 36,
    name: "Harry Kane",
    foot: "DX",
    nationality: "Inghilterra",
    role: "ATT",
    trophies: ["Bundesliga"],
    speciality: ["Finalizzazione", "Gioco spalle alla porta"],
    height: 188,
    careerGoals: 380,
    image: "images/kane.jpg"
  },
  {
    id: 37,
    name: "Luis Suárez",
    foot: "DX",
    nationality: "Uruguay",
    role: "ATT",
    trophies: ["Champions League", "Liga"],
    speciality: ["Aggressività", "Finalizzazione"],
    height: 182,
    careerGoals: 530,
    image: "images/suarez.jpg"
  },
  {
    id: 38,
    name: "Antoine Griezmann",
    foot: "SX",
    nationality: "Francia",
    role: "ATT",
    trophies: ["Liga"],
    speciality: ["Movimento", "Versatilità"],
    height: 176,
    careerGoals: 280,
    image: "images/griezmann.jpg"
  },
  {
    id: 39,
    name: "Eden Hazard",
    foot: "DX",
    nationality: "Belgio",
    role: "ATT",
    trophies: ["Premier League"],
    speciality: ["Dribbling", "Cambio di direzione"],
    height: 175,
    careerGoals: 200,
    image: "images/hazard.jpg"
  },
  {
    id: 40,
    name: "Raheem Sterling",
    foot: "DX",
    nationality: "Inghilterra",
    role: "ATT",
    trophies: ["Premier League"],
    speciality: ["Tagli", "Velocità"],
    height: 170,
    careerGoals: 180,
    image: "images/sterling.jpg"
  },
  {
    id: 41,
    name: "Jadon Sancho",
    foot: "DX",
    nationality: "Inghilterra",
    role: "ATT",
    trophies: ["Bundesliga"],
    speciality: ["Dribbling", "Creatività"],
    height: 180,
    careerGoals: 85,
    image: "images/sancho.jpg"
  },
  {
    id: 42,
    name: "Phil Foden",
    foot: "SX",
    nationality: "Inghilterra",
    role: "CEN",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Tecnica", "Inserimenti"],
    height: 171,
    careerGoals: 90,
    image: "images/foden.jpg"
  },
  {
    id: 43,
    name: "Joshua Kimmich",
    foot: "DX",
    nationality: "Germania",
    role: "CEN",
    trophies: ["Champions League", "Bundesliga"],
    speciality: ["Versatilità", "Passaggi"],
    height: 176,
    careerGoals: 65,
    image: "images/kimmich.jpg"
  },
  {
    id: 44,
    name: "Thomas Müller",
    foot: "DX",
    nationality: "Germania",
    role: "ATT",
    trophies: ["Champions League", "Bundesliga"],
    speciality: ["Inserimenti", "Spazio", "Assist"],
    height: 185,
    careerGoals: 310,
    image: "images/muller.jpg"
  },
  {
    id: 45,
    name: "Son Heung-min",
    foot: "DX",
    nationality: "Corea del Sud",
    role: "ATT",
    trophies: [],
    speciality: ["Contropiede", "Finalizzazione"],
    height: 183,
    careerGoals: 250,
    image: "images/son.jpg"
  },
  {
    id: 46,
    name: "Rúben Dias",
    foot: "DX",
    nationality: "Portogallo",
    role: "DIF",
    trophies: ["Champions League", "Premier League"],
    speciality: ["Marcatura", "Leadership"],
    height: 187,
    careerGoals: 18,
    image: "images/dias.jpg"
  },
  {
    id: 47,
    name: "Aymeric Laporte",
    foot: "SX",
    nationality: "Spagna",
    role: "DIF",
    trophies: ["Premier League"],
    speciality: ["Impostazione", "Gioco aereo"],
    height: 189,
    careerGoals: 22,
    image: "images/laporte.jpg"
  },
  {
    id: 48,
    name: "Kalidou Koulibaly",
    foot: "DX",
    nationality: "Senegal",
    role: "DIF",
    trophies: ["Serie A"],
    speciality: ["Fisicità", "Contrasti"],
    height: 187,
    careerGoals: 25,
    image: "images/koulibaly.jpg"
  },
  {
    id: 49,
    name: "Achraf Hakimi",
    foot: "DX",
    nationality: "Marocco",
    role: "DIF",
    trophies: ["Serie A", "Ligue 1"],
    speciality: ["Velocità", "Spinta offensiva"],
    height: 181,
    careerGoals: 45,
    image: "images/hakimi.jpg"
  },
  {
    id: 50,
    name: "Jude Bellingham",
    foot: "DX",
    nationality: "Inghilterra",
    role: "CEN",
    trophies: ["Champions League", "Liga"],
    speciality: ["Inserimenti", "Fisicità", "Leadership"],
    height: 186,
    careerGoals: 70,
    image: "images/bellingham.jpg"
  }
];
